// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/VI-IM/im_backend_go/ent/otp"
	"github.com/VI-IM/im_backend_go/ent/schema"
	"github.com/VI-IM/im_backend_go/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	otpFields := schema.OTP{}.Fields()
	_ = otpFields
	// otpDescIsUsed is the schema descriptor for is_used field.
	otpDescIsUsed := otpFields[4].Descriptor()
	// otp.DefaultIsUsed holds the default value on creation for the is_used field.
	otp.DefaultIsUsed = otpDescIsUsed.Default.(bool)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescIsAdmin is the schema descriptor for is_admin field.
	userDescIsAdmin := userFields[3].Descriptor()
	// user.DefaultIsAdmin holds the default value on creation for the is_admin field.
	user.DefaultIsAdmin = userDescIsAdmin.Default.(bool)
	// userDescIsActive is the schema descriptor for is_active field.
	userDescIsActive := userFields[4].Descriptor()
	// user.DefaultIsActive holds the default value on creation for the is_active field.
	user.DefaultIsActive = userDescIsActive.Default.(bool)
}
