name: Build and Push Go Backend Docker Image (with Frontend)

on:
  push:
    branches:
      - '**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # ✅ Checkout backend repo (current)
      - name: Checkout Backend Repo
        uses: actions/checkout@v3

      # ✅ Checkout frontend repo
      - name: Checkout Frontend Repo
        uses: actions/checkout@v3
        with:
          repository: Deepuprajapat/new_ft
          path: frontend
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      # ✅ Build frontend with CI=false to ignore lint errors
      - name: Build and zip frontend
        run: |
          cd frontend
          npm install
          CI=false npm run build
          zip -r ../frontend.zip build/

      # ✅ Move ZIP to backend folder
      - name: Copy zip to backend
        run: |
          mkdir -p backend/static-zip
          cp frontend.zip backend/static-zip/frontend.zip

      # ✅ Login to GHCR (only on main)
      - name: Log in to GHCR
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      # ✅ Setup variables
      - name: Set up commit hash and lowercase repo
        run: |
          echo "SHORT_SHA=${GITHUB_SHA::8}" >> $GITHUB_ENV
          echo "REPO_LOWER=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      # ✅ Build Docker image (from backend folder)
      - name: Build Docker Image
        run: |
          cd backend
          docker build -t ghcr.io/${{ env.REPO_LOWER }}:${{ env.SHORT_SHA }} .
          docker tag ghcr.io/${{ env.REPO_LOWER }}:${{ env.SHORT_SHA }} ghcr.io/${{ env.REPO_LOWER }}:latest

      # ✅ Push both tags to GHCR
      - name: Push Docker Image
        if: github.ref == 'refs/heads/main'
        run: |
          docker push ghcr.io/${{ env.REPO_LOWER }}:${{ env.SHORT_SHA }}
          docker push ghcr.io/${{ env.REPO_LOWER }}:latest
