name: Build and Push Go Backend Docker Image

on:
  push:
    branches:
      - '**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # ✅ Build the frontend app
      - name: Build Frontend
        run: |
          cd frontend
          npm install
          npm run build
          cd ..
          mkdir -p backend/frontend
          cp -r frontend/build/* backend/frontend/

      # ✅ Login to GitHub Container Registry (only on main branch)
      - name: Log in to GHCR
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      # ✅ Set variables (commit SHA and repo name lowercase)
      - name: Set up commit hash and lowercase repo
        id: vars
        run: |
          echo "SHORT_SHA=${GITHUB_SHA::8}" >> $GITHUB_ENV
          echo "REPO_LOWER=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      # ✅ Build Docker Image
      - name: Build Docker Image
        run: |
          cd backend
          docker build -t ghcr.io/${{ env.REPO_LOWER }}:${{ env.SHORT_SHA }} .

      # ✅ List docker images
      - name: List docker images
        run: docker images

      # ✅ Push Docker Image to GHCR (only on main branch)
      - name: Push Docker Image
        if: github.ref == 'refs/heads/main'
        run: |
          docker push ghcr.io/${{ env.REPO_LOWER }}:${{ env.SHORT_SHA }}

